### PR TITLE
fix: internal error: unexpected: negative sleep time: 0s

### LINKED ISSUE #124: cogito: error: put: internal error: unexpected: negative sleep time: 0s
Just observed in our deployment:

```
[INFO]  cogito: This is the Cogito GitHub status resource. Tag: 0.10.1, commit: 05c92db, build date: 2023-05-31
[INFO]  cogito.put.ghCommitStatus: GitHub HTTP request: attempt=1 max=3
[INFO]  cogito.put.ghCommitStatus: Sleeping for: time=4m47s
[INFO]  cogito.put.ghCommitStatus: GitHub HTTP request: attempt=2 max=3
cogito: error: put: internal error: unexpected: negative sleep time: 0s
```

See also #123.

### PR DESCRIPTION
**Pull request by marco-m-pix4d**
Closes #124 and PCI-3302.

Best reviewed commit-per-commit and looking at the commit comments, otherwise it will be impossible to understand the details, and we do need to understand them in this case. Each commit tells the story and carefully builds on the precedent, keeping code coverage 100% (this doesn't ensure anything but is better than not doing it).

Last commit is perhaps the most unexpected, were we "define the errror out of existence", in the spirit of the book "A Philosophy of Software Design" by John Ousterhout (Talk: https://youtu.be/bmSAYlu0NcY?t=1313).

I have a recollection that the reason for the existence of the error is a comment I made on a previous PR by Aleksandar, so I am undoing what I proposed, because I learned from experience.

I decided not to touch the jitter initialization on purpose, because I think that the code in this PR is more robust and still as simple as it can. I am open to discussion.

### CODE REVIEW

File: github/commitstatus.go [hunk 1]
```diff
@@ -262,35 +259,46 @@ func min(a, b int) int {
...
+	if res.statusCode == http.StatusForbidden && res.rateLimitRemaining == 0 {
 		// Calculate the sleep time based solely on the server clock. This is unaffected
 		// by the inevitable clock drift between server and client.
 		sleepTime := res.rateLimitReset.Sub(res.date)
+		// Be robust to possible races in the GitHub backend. This avoids failing too early.
+		if sleepTime < 0 {
+			sleepTime = 0
+		}
 		// Be a good netizen by adding some jitter to the time we sleep.
 		sleepTime += jitter
```
Comment (aliculPix4D) [inline github/commitstatus.go:283]: I will check again tomorrow but I think your PR still doesn't fix the situation that I think it happend (which is actually the simplest possible case)

- first request failed. Sleep time was around 4min30sec
- so we sleep this time
- second request is done. lets assume `res.rateLimitReset.Sub(res.date)` returned 0.
- by pure luck jitter rand func also returned 0
- even if we had your current code, third attempt would never happen because we brake out of the loop

**Review by odormond — APPROVED** [review]

File: github/commitstatus.go (hunk 1 above)
Comment (odormond) [reply github/commitstatus.go:283]: You might not be talking to the same server on both attempts. They might have clocks off by just the right amount such that the second requests appears to arrive milliseconds before the reset.

But your point is still valid so probably making sure jitter is at least 1 would be an easy fix.

File: github/commitstatus.go [hunk 2]
```diff
@@ -262,35 +259,46 @@ func min(a, b int) int {
...
+
 		switch {
+		case sleepTime == 0:
+			return 0, ""
```
Comment (aliculPix4D) [inline github/commitstatus.go:287]: I would add a msg here because this will terminate the loop without succesfull request, so the situation is quite different than:
```
case sleepTime > maxSleepTime:
   return 0, ""
```

File: github/commitstatus.go (hunk 1 above)
Comment (marco-m-pix4d) [reply github/commitstatus.go:283]: @aliculPix4D 
I don't understand this scenario. Now that we have the dedicated unit test, can you come up with a test that shows the bug? If not, I think it is better to have a face chat so that I can understand the details.

Comment (marco-m-pix4d) [reply github/commitstatus.go:283]: > so probably making sure jitter is at least 1 would be an easy fix.

If the scenario turns out to be possible, I agree that this for sure is an easy fix.

File: github/commitstatus.go (hunk 2 above)
Comment (marco-m-pix4d) [reply github/commitstatus.go:287]: There is no message because the current client code would not print such message.

> because this will terminate the loop without successful request

Ah. Let me check.

File: github/commitstatus.go (hunk 1 above)
Comment (aliculPix4D) [reply github/commitstatus.go:283]: I would suggest you also change the jitter time to:
`5*time.Second + time.Duration(rand.Intn(30)) * time.Second`
https://github.com/Pix4D/cogito/blob/389e9a79e6622c6edc9fcdeb6119122a33b4db97/cogito/ghcommitsink.go#L43

File: github/commitstatus.go (hunk 2 above)
Comment (aliculPix4D) [reply github/commitstatus.go:287]: Ok. I see why there is no msg.

But as we discussed in person, if the request failed, we would break the loop and the next attempt would not happen.
and in `checkStatus` we would inform the user we failed due to being rate limited and you had to wait just 0 seconds.

File: github/commitstatus.go (hunk 1 above)
Comment (marco-m-pix4d) [reply github/commitstatus.go:285]: As discussed face-to-face, I did not change the jitter on purpose. The code must be correct also if jitter equals 0.

File: github/commitstatus.go (hunk 2 above)
Comment (marco-m-pix4d) [reply github/commitstatus.go]: Resolving conversation as the code changed a lot, and the changes address also this.

**Comment by marco-m-pix4d** [comment]
@Pix4D/integration: ready for re-review.
Thanks for @aliculPix4D for spotting the suble new bug of the subtle existing bug.
Please follow the new commits with their comments, they explain what is happening and step by step also simplify the logic.

**Review by aliculPix4D — APPROVED** [review]
LGTM.

You were correct, this is much better and way simpler. Thanks

Don't forget to close:
https://github.com/Pix4D/cogito/issues/124
https://github.com/Pix4D/cogito/issues/125

one is already solved, other is solved when you merge this PR.

**Comment by marco-m-pix4d** [comment]
> Don't forget to close:
#124
#125

To double-check nothing is missing:

since #124 is mentioned in this PR (or in a commit comment), it will be closed automatically:
pr

while #125 is unrelated.

In my understanding, there is nothing to do. Am I missing something?

**Comment by aliculPix4D** [comment]
> In my understanding, there is nothing to do. Am I missing something?

no, it was my mistake: I was thinking of #/123 and for the other #124, I didn't know, it will be closed automatically:
